### ISSUE TITLE
Missing required package PyPDF2 and incorrect sample commandline

### ISSUE THREAD

**Issue by Toroid42** [nacrul-eth/chainreport-converter#24]
Before the script can be executed the Python package PyPDF2 is required

`pip install PyPDF2`

And the given command in the README

`=> python3 src/chainreport_converter_script.py Hi hi-statement.csv chainreport.csv`

Is not working as "Hi" is not available but "Hi-CSV" and "Di-PDF"

**Comment by nacrul-eth** [comment]
Thanks for reporting the issue. 
It should be fixed and correctly documented with the linked pull request. 
If you still encounter issues, please reopen the issue.
