### ISSUE TITLE
Converter beendet sich mit "[WARNING] stderr: KeyError: 'Description'"

### ISSUE THREAD

**Issue by Dav1t09** [nacrul-eth/chainreport-converter#38]
Beim Versuch die csv für die Rewards aus dem Plutus analytics dashboard für chain.report zu konvertieren, beendet sich der Parser mit der folgenden Meldung im Log:

[INFO   ] Base: Start application main loop
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "chainreport_converter_app.py", line 103, in <module>
[WARNING] stderr:     ChainreportConverterApp().run()
[WARNING] stderr:   File "kivy\app.py", line 956, in run
[WARNING] stderr:   File "kivy\base.py", line 574, in runTouchApp
[WARNING] stderr:   File "kivy\base.py", line 339, in mainloop
[WARNING] stderr:   File "kivy\base.py", line 383, in idle
[WARNING] stderr:   File "kivy\base.py", line 334, in dispatch_input
[WARNING] stderr:   File "kivy\base.py", line 302, in post_dispatch_input
[WARNING] stderr:   File "kivy\\_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
[WARNING] stderr:   File "kivy\uix\behaviors\button.py", line 179, in on_touch_up
[WARNING] stderr:   File "kivy\\_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
[WARNING] stderr:   File "kivy\\_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
[WARNING] stderr:   File "kivy\\_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
[WARNING] stderr:   File "kivy\lang\builder.py", line 60, in custom_callback
[WARNING] stderr:   File "C:\Users\xyz\AppData\Local\Temp\_MEI376642\chainreportconverter.kv", line 76, in <module>
[WARNING] stderr:     on_release: root.start_conversion()
[WARNING] stderr:   File "chainreport_converter_app.py", line 84, in start_conversion
[WARNING] stderr:     self.converter_object.convert(self.log_action)
[WARNING] stderr:   File "chainreport_converter.py", line 208, in convert
[WARNING] stderr:     self.convert_csv(writer, _logging_callback)
[WARNING] stderr:   File "chainreport_converter.py", line 141, in convert_csv
[WARNING] stderr:     if current_linedata.check_if_skip_line():
[WARNING] stderr:   File "chainreport_parser\plutus_parser_csv.py", line 29, in check_if_skip_line
[WARNING] stderr: KeyError: 'Description'

Mehrmals versucht mit dem selben Resultat. Was ist hier das Problem?

**Comment by nacrul-eth** [comment]
Bei dem letzten Update hat sich leider ein Tippfehler eingeschlichen. 
Das Problem ist schon behoben, aber ich habe noch keinen neuen Release gemacht. 
Werde ich morgen versuchen und nochmal Bescheid geben. 
Danke fürs melden!

**Comment by nacrul-eth** [comment]
Fixed in #37 
@Dav1t09  Ich habe einen neuen Release v0.0.6 erstellt, welcher das Problem behoben haben sollte.
Falls es noch Probleme gibt, melde dich nochmal.
